### ISSUE TITLE
Did your implementation consider the problem of weight decay in Adam?

### ISSUE THREAD

**Issue by jiang-yuan** [phizaz/cprop#2]
Do you change the way to implement weight decay in cpropadam as in adamW?

**Comment by konpatp** [comment]
@jiang-yuan It does not. I think it is a bad idea to incorporate the effect of weight decay in CProp. In other words, **CProp should not see the gradient incurred by weight decay (which is something the implementation does wrongly).**

**Comment by jiang-yuan** [comment]
> 
> 
> @jiang-yuan It does not. I think it is a bad idea to incorporate the effect of weight decay in CProp. In other words, **CProp should not see the gradient incurred by weight decay (which is something the implementation does wrongly).**

Do you mean that I should always keep weight decay parameter in cpropadam euquals to 0.0?

**Comment by konpatp** [comment]
@jiang-yuan Weight decay = 0.0 is the well-explored one. Weight decay > 0, retrospectively, I think the current implementation is not ideal because the gradient is "modified in-place" by the weight decay. A better implementation should be that CProp never sees the artificially inflated gradient.

**Comment by jiang-yuan** [comment]
> 
> 
> @jiang-yuan Weight decay = 0.0 is the well-explored one. Weight decay > 0, retrospectively, I think the current implementation is not ideal because the gradient is "modified in-place" by the weight decay. A better implementation should be that CProp never sees the artificially inflated gradient.

OK. I am looking for an optimizer that without the effort to tryLR schedules or tunning other parameters. I think this is what I need. Thank you.
